#!/bin/bash

usage()
   {
      echo "usage:"
      echo "   My help                       -- get this screen"
      echo "   My name                       -- get my name"
      echo "   My cert    {create|revoke}    -- create or remove my certificate"
      echo "   My project list               -- list my projects"
      echo "   My project <name> {+|-|=} pat -- grant, revoke or list permission of a named project"
      echo ""
      echo "where 'pat' is a pattern:"
      echo " - either an email address"
      echo " - or a local name (see 'My name')"
      echo ""
      exit 0
   }

case "$1"
   in
      name)               echo "$GL_USER"; exit 0;;
      cert|c|certificate) 
            case "$2"
               in
                  create) ssh root@authorize mk_client_cert --download "${GL_USER}" "$3";;
                  revoke) ssh root@authorize rm_client_cert            "${GL_USER}"     ;;
                  *)      echo "cert '$2' is NOT supported" >&2; usage;;
               esac
         ;;
      project|p|proj)     :;;
      *)                  usage;;
   esac
